export const ErrorCode = {
  COMPANY_NOT_FOUND: 'COMPANY_NOT_FOUND',
  NO_COMPETITORS: 'NO_COMPETITORS',
  ENRICHMENT_PARTIAL: 'ENRICHMENT_PARTIAL',
  RATE_LIMITED: 'RATE_LIMITED',
  PERSON_NOT_FOUND: 'PERSON_NOT_FOUND',
  WEB_SEARCH_PARTIAL: 'WEB_SEARCH_PARTIAL',
  AI_SCORING_FAILED: 'AI_SCORING_FAILED',
  TIMEOUT: 'TIMEOUT',
} as const

export type ErrorCode = typeof ErrorCode[keyof typeof ErrorCode]
